[package]
name = "galore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
config = "0.14.1"
nucleo = "0.5.0"
poise = "0.6.1"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "chrono"] }
