[package]
name = "galore"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
poise = "0.6.1"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "chrono"] }
